django/mydjango23/accounts/urls.py
from django.urls import path
from accoints import views

app_name = "account"

urlpatterns = [
    path("profile.png", views.profile_image, name = "profile_image")
    path('login/', views.login, name = 'login'),
    path('signip/', views.signup, name = "signup"),
    path('profile/', views.profile, name = "profile"),
    path('logout/', views.logout, name = "logout"),
]

django/mydjango23/blog/urls.py
from django.urls import path

from blog.views import fbv as views
# from blog.views import cbv as views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("new/", views.post_new, name="post_new"),
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("<int:pk>/delete/", views.post_delete, name="post_delete"),
    path('subscruber/new', views.subscriber_new, name="subscriber_new"),
]

django/mydjango23/mydjango23/urls.py
url
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from mydjango23.settings import DEBUG

from django.shortcuts import redirect
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', includ('accounts.urls')),
    # FIXME: 아래의 url 설정은 blog 기능 구현 후에 pattern_name 으로 변경 예정
    path('', RedirectView.as_view(url='/blog/'), name = 'root'),
]

# static의 반환값은 리스트!!
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if DEBUG:
    import debug_toolbar
urlpatterns += [
    path('__debug__/', include(debug_toolbar.urls)),
]

django/mydjango23/blog/models.py
from django.db import models

class TimestampledModel(models.Model):
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Category(TimestampledModel):
    name = models.CharField(max_length = 100, unique = True)

    def __str__ (self) -> str:
        return self.name

    class Meta:
        ordering = ['name']

class Post(TimestampledModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length = 200, db_index = True)
    content = models.TextField()
    photo = models.ImageField(upload_to='blog/post/%Y/%m/%d')
    tag_set = models.ManyToManyField('Tag', blank = True)
    status = models.CharField(
        max_length = 1,
        # FIXME: 장고 3에서 추가된 TextChoices 기능을 활용
        choices = [
            ('D','초안'),  # Draft // DB저장값, Label
            ('P',"공개"),   # Published
        ],
        db_index = True,
        default = 'D', # 이것으로 초기값 설정
    )

    def __str__ (self):
        return self.title

    # post detail 주소 문자열을 반환
    # detail 페이지를 구현하자마자, 즉시 아재 메서드를 구현합니다.
    def get_absolute_url(self)-> str: 
        return reverse('blog:post_detail', args=[self.pk])

    @classmethod
    def get_xlsx_data(cls, queryset ,format="xisx")-> bytes:
        dataset = tablib.Dateset()
        dataset.headers = ["id", "title", "created_at", "updated_at"]

        for post in queryset:
            dataset.append(
                [
                    post.id
                    post.title
                    post.created_at.strftime("%Y-%m-%d %H:%M:%S")
                    post_updated_at.strftime("%Y-%m-%d %H:%M:%S")
                ]
            )

        # xlsx_data = dataset.export(format)
        # return xlsx_data
        return dataset.export(format)            

    class Meta:
        ordering = ['-id']

class Comment(TimestampledModel):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    message = models.TextField()

    def __str__ (self):
        return self.message

    class Meta:
        ordering = ['-id']

class Tag(TimestampledModel):
    name = models.CharField(max_length = 20, unique = True)

    def __str__ (self):
        return self.name

    class Meta:
        ordering = ["name"]


class Subscriber(TimestampledModel):
    phone = models.CharField(
        max_length=15,
        validators = [
            RegexValidator(r"^\d{3,4}-?\d{3,4}-?\d{4}$"),
        ]
    )

django/mydjango23/blog/forms.py
from django import forms
from blog.models import Post

class PostForm(forms.ModelForm):
    tags = forms.CharField()
    class Meta:

        # 초기값 지정
        def __init__(self, *args, **kwargs):
            super().__init(*args, **kwargs)

            if self.instance.pk:
                tag_qs = self.instance.tag_set.all()
                initial = ", ".join([tag.name for tag in tag_qs])
                self.fields["tags"].initial= "..."

        # DB로의 저장

        # def save(self, commit = True):
        #   saved_post = super().save(commit)
        #   return saved_post
        # 아래 함수가 호출되기 전에, instance.save()가 호출되었음을 보장받습니다.
        def _save_m2m(self):
            super()._save_m2m()

            tag_list = []
            tags = self.cleaned_data.get("tags","")
            for word in tags.split(","):
                tag_name = word.strip()
                tag, __ = Tag.objects.get_or_create(name = tag_name)
                tag_list.append(tag)

            self.instance.tag_set.clear()
            self.instance.tag_set.add(*tag_list)

        def clean_content(self):
            conent = self.cleaned_data.get("content")
            if content:
                # Script 태그를 제거
                content = re.sub(r"<script.*?>.*?</script>","",content,flags = re.I |re.S)
                return content

        model = Post
        fields = [
            "category",
            "title",
            "content",
            'photo',
            'status',
        ]

class SubscriberForm(forms.ModelForm):
    class Meta:
        models = Subscriber
        fields = "__all__"

    # Form 만의 유효성 검사 방법 + 데이터 변환 기능 제공
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if phone: # phone 값이 있을 때,
            if not phone.startswitch("010"):
                raise forms.ValidationError("010으로 시작토록 입력해주세요.")
        return phone.replace("-","")

django/mydjango23/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm  
from django.views.generic import CreateView
from PIL import Image

from Login.views import LoginView
from django.contrib.auth import views

login = LoginView.as_view(
    form_class = LoginForm,
    template_name="accounts/login_form.html",
)

# 새로운 User 인스턴스를 만드는 것.
def signup(request):
    if request.method == "POST"
        form = UserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redurect("accounts:login")
    else:
        form = UserCreateionForm()
    return render(request, "accounts/signup_form.html",{'form':form},)

# signup = CreateView.as_view(
#     form_class = UserCreationForm,
#     success_url = reverse_lazy("accounts:login"),
#     template_name = "accounts/signup_form/html",
# )

@login_required # 로그인이 필요하다는 의미를 가지고 있음.
def profile(request:HttpRequest)->HttpResponse:
    return render(request, "blog/profile.html")

logout = LogoutView.as_view(
    next_page = "accounts:login",
)

django/mydjango23/accounts/templates/accounts/layout.html
{% extends "layout.html" %} {% block extra_head %}

<style>
  body {
    background-color: lightblue;
  }
</style>

{% endblock %}

django/mydjango23/accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %} {% black content %}
<h2>Login Form</h2>
<form action="" method="post" enctype="multipart/form-data">
  <table>
    {{ form.sd_table }}
  </table>
</form>
{% endblock %}

django/mydjango23/accounts/templates/accounts/profil.html
{% extends "accounts/layout.html" %} {% block content %}
<h2>{{ user }}'s Profile</h2>
{% endblock %}

<!--
Anonymous -> 익명 user
-->

django/mydjango23/accounts/templates/accounts/singup_form.html
{% extends "accounts/layout.html" %} {% block content %}
<h2>
  회원 가입
  <h2>
    <form action="" method="post" , enctye="multipart/form-data">
      {% csrf_token %}
      <table>
        {{form.as_table}}
      </table>

      <input type="submit" value="회원가입 신청" />
    </form>

    {% endblock %}
  </h2>
</h2>

django/mydjango23/blog/templates/blog/layout.html
{% extends "layout.html" %} {% block extra_head %}

<style>
  body {
    background-color: lightyellow;
  }
</style>

{% endblock %}

django/mydjango23/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/layout.html' %} {% block content %}

<h2>Post 삭제를 확인</h2>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="삭제하겠습니다." />
</form>

<hr />
<a href="{% url "blog:post_detail" post.pk %}"> Detail로 돌아가기 </a>

{% endblock %}

django/mydjango23/blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %} {% block page_title %} {{ block.super }} :: {{
post.title }} {% endblock %} {% block content %}

<h2>{{post.title}}</h2>

<p>{% for tag in post_tag_set.all %} {{tag.name}} {% endfor %}</p>

<img src="{{post.photo.url}}" alt="{{ post.title }}" />

{{ post.content | linebreaks }}

<hr />
<a href="{% url 'blog:post_list' %}"> 포스팅 목록 </a>
<a href="{% url 'blog:post_edit' post.pk %}"> 포스팅 수정 </a>
<a href="{% url 'blog:post_delete' post.pk %}"> 포스팅 삭제 </a>

{% endblock %}

django/mydjango23/blog/templates/blog/post_form.html
{% extends 'blog/layout.html' %} {% block content %}

<form action="" method="post" entype="multipart/form-data" novalidate>
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit" />
 
  </form>

  <hr />
  <a href = "{% url "blog:post_list"  %}">
  목록으로
  </a>

  {% if post %}
        <a href="{% url "blog:post_detail" post.pk %}">
            조회화면으로
        </a>
  {% endif %}
</form>

 {% endblock %}

django/mydjango23/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %} {% block content %}
    <h2> Post List </h2>

    <table>
        <thead>
            {% for post in post_list %}
                <tr>
                    <td>
                        <a href = "{% url "blog:post_detail" post.pk %}">
                            {{post.title}}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </thead>
    </table>

    <hr />
    <a href = "{% url "blog:post_new" %}">
    포스팅 쓰기
    </a>
{% endblock %}

django/mydjango23/blog/templates/blog/subscriber.form.html
{% extends 'blog/layout.html' %} {% block content %}
<h2>Subscriber Form</h2>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" />
</form>
{% endblock %}