django/mydjango19_1/mydjango17/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from mydjango17.settings import DEBUG

from django.shortcuts import redirect

# TODO: 편의상 여기에 root를 구현하지만,
# 차후 RedirectView CBV를 써서 이 구현을 제거할 예정

# 자동으로 페이지 이동 구현


def root(request):
    return redirect("second:second_list")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('second/', include('second.urls')),
    path('', root, name='root'),
]

# static의 반환값은 리스트!!
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if DEBUG:
    import debug_toolbar
urlpatterns += [
    path('__debug__/', include(debug_toolbar.urls)),
]

django/mydjango19_1/second/urls.py
from . import views
from django.urls import path

app_name = "second"

# 2)
urlpatterns = [
    path('', views.second_list, name="second_list"),
    path('<int:pk>/', views.second_detail, name="second_detail"),
    path("new/", views.post_name, name="post_new"),
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path('tags/<str:tag_name>/', views.tag_detail, name="tag_detail"),
    path("<int:post_pk>/comment/new/",views.comment_new, name = "comment_new"),
    path("<int:post_pk>/comment/<int:pk>/edit/",views.comment_edit, name = "comment_edit"),
    

]

django/mydjango19_1/second/models.py
from abc import abstractmethod
from django.db import models
from django.core.validators import MaxLengthValidator, MinLengthValidator

# 3)


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # 추상 클래스로서, DB 테이블이 생기지 않습니다.

# 1) - # 4) models.Model 의 TimestampedModel 추가

class Category(TimestampedModel):
    name = models.CharField(max_length=100,unique=True)

    def __str__(self) -> str:
        return self.name


class Second(TimestampedModel):
    # Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # 7) auth_name 추가(add)
    auth_name = models.CharField(max_length=100)
    tite = models.CharField(
        max_length=100,
        db_index=True,
        validators=[
            MinLengthValidator(3),
            # MaxLengthValidator(),
        ])
    content = models.TextField()
    photo = models.ImageField(upload_to="second/second/%Y/%m/%d")
    ip = models.GenericIPAddressField()

    # 5) ManyToManyField
    tag_set = models.ManyToManyField('tag', blank=True)

    # 8)
    def __Str__(self)-> str :
        return f"[{self.pk}] {self.tite}"

    # 10)
    class Meta:
        verbose_name = "포스팅"
        verbose_name_plural = "포스팅 목록"
# 2)

# 2) 안에 #6) 댓글


class Comment(TimestampedModel):
    # 7) auth_name 추가(add)
    # 11) second 추가

    # 외래키 : 정수값
    second = models.ForeignKey(Second, on_delete=models.CASCADE)
    # second_id 자동생성
    auth_name = models.CharField(max_length=100)
    message = models.TextField()

    # 10)
    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글 목록"


class tag(TimestampedModel):
    name = models.CharField(max_length=100, db_index=True)

    # many-to-many
    # second_set = models.ManyToManyField('Second') 이렇게 해도 가능

    # 9)
    def __str__(self) -> str:
        return self.name

        # 10)
    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그 목록"

django/mydjango19_1/second/forms.py
# from django import forms
# from django.core.validators import RegexValidator


# class PostForm(forms.Form):
#     title = forms.CharField()
#     content = forms.CharField()
#     phone = forms.CharField(
#         validators=[
#             RegexValidator(r"^\d{3}-?\d{4}-?\d{4}$",
#                            message="휴대폰 번호를 입력해주세요."),
#         ]
#     )

from django import forms
from second.models import Second, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Second
        # fields = "__all__"

        # 유저로부터 입력받을 필드 이름을 나열
        fields = [
            "auth_name",
            "tite",
            "content",
            "photo",
            "tag_set",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = "__all__"
        fields = [
            "auth_name",
            "message",
        ]

django/mydjango19_1/second/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.http import HttpRequest, HttpResponse, Http404
from django.contrib import messages
from second.models import Second, Comment
from second.forms import PostForm , CommentForm


def tag_detail(request: HttpResponse, tag_name: str) -> HttpRequest:
    qs = Second.objects.all()
    qs = qs.filter(tag_set__name=tag_name)
    app_name = 'second/tag_detail.html'
    context_data = {"tag_name": tag_name, "second_list": qs}
    return render(request, app_name, context_data)


def second_list(request: HttpRequest) -> HttpResponse:
    app_name = 'second/second_list.html'
    qs = Second.objects.all()
    query = request.GET.get("query", "")
    if query:
        qs = qs.filter(tite__icontains=query)
    context_data = {"second_list": qs}

    return render(request, app_name, context_data)


def second_detail(request: HttpRequest, pk: int) -> HttpResponse:

    post = get_object_or_404(Second, pk = pk)
    
    app_name = 'second/second_detail.html'
    second = Second.objects.get(pk=pk)
    comment_list = second.comment_set.all()
    tag_list = second.tag_set.all()

    context_data = {
        'second_detail': second,
        "comment_list": comment_list,
        'tag_list': tag_list, }

    return render(request, app_name, context_data)


def post_name(request: HttpRequest) -> HttpResponse:

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            form.save()  # ModelForm에서만 지원
            messages.success(request, "성공적으로 저장했습니다.")
            return redirect('second:second_list')
    else:
        form = PostForm()

    return render(request, "second/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Second, pk = pk)


    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post.save()
            messages.success(request, "성공적으로 수정했습니다.")
            return redirect('second:second_list')
    else:
        form = PostForm(instance=post)

    return render(request, "second/post_form.html", {
        "form": form,
    })

# /second/100/comment/new/
def comment_new(request:HttpResponse, post_pk:int) -> HttpResponse:
    post = get_object_or_404(Second, pk = post_pk)
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.second= post
            comment.save()
            return redirect('second:second_detail', post_pk)
    else:
        form = CommentForm()
    return render(request,'second/comment_form.html',{"comment":form,})

# second/100/comments/20/edit
def comment_edit(request:HttpResponse , post_pk:int , pk:int) -> HttpResponse:

    comments = get_object_or_404(Comment, pk = pk)
    # 수정
    if request.method == "POST":
        form = CommentForm(request.POST,request.FILES,instance=comments)
        if form.is_valid():
            form.save()
            return redirect('second/second_detail', post_pk )
    else:
        form = CommentForm(instance = comments)
    return render(request, 'second/comment_form.html',{
        'form':form,
    })

django/mydjango19_1/second/templates/second/comment_form.html
{% extends "second/layout.html" %}
{% load bootstrap5 %}

{% block content %}

    <h2>Comment form</h2>
    
    <!-- 검색은  = get   ,  파일전송 = post -->
    <form action="" method = "post" enctype="multipart/form-data">
        <!-- csrf_token 은 post 일 때만 사용하지 -->
        {% csrf_token %} 
        {% bootstrap_form form %}
        <input type="submit", value = '검색하기' class="btn btn-primary">
    </form>
    
{% endblock %}

django/mydjango19_1/second/templates/second/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>누구누구의 다이어리</title>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src = '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js'></script>
<!-- ------------------------------------------ -->
    <style>
      body{
        padding-bottom: 1em;
      }
    </style>
<!-- ------------------------------------------ -->
  </head>
<body>

    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="{% url 'root' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
              <span class="fs-4">누구누의 블로그</span>
            </a>

            <ul class="nav nav-pills">
              <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
              <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
              <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
              <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
              <li class="nav-item"><a href="#" class="nav-link">About</a></li>
            </ul>
        </header>
        <!-- 어 왜 사라지지?? -->
        <!-- 다른언어에는 [플레쉬]__메시지 라고 함. -->
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
              {{message}}
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
        <hr />
        &copy; 2021 누구누구 컴퍼니
    </div>



  
</body>
</html>

django/mydjango19_1/second/templates/second/post_form.html
{% extends "second/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>Post Form</h2>
    
    <form action="" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        <input type="submit" value="저장하기">
    </form>
{% endblock %}

django/mydjango19_1/second/templates/second/second_detail.html
{% extends 'second/layout.html' %}
{% block content %}

    <h2>{{second_detail.tite}}</h2>

    <p>
        태그:
        {% for tag in tag_list %}
            <a href="{% url 'second:tag_detail' tag.name %}" class = "badge bg-success">
                {{tag.name}}
            </a>    
        {% endfor %}
    </p>

<!-- -------------------------------------------------------------------------------------- -->

    <img src = "{{ second_detail.photo.url}}" alt="{{second_detail.title}}" />
    {{ second_detail.content|linebreaks }}

    <h3>댓글</h3>

    <a href="{% url 'second:comment_new' second_detail.pk %}">댓글쓰기</a>
    
    <ul>
        {%for comment in comment_list %}
        <li>
            {{comment.message}}
            by {{comment.author_name}}
            at 
            <span tite = '{{comment.created_at}}' >
                {{comment.created_at|timesince}} 전
            </span>

            <a href="{% url 'second:comment_edit' second_detail.pk comments.pk %}">
                수정하기
            </a>
        </li>
        {% endfor %}
    </ul>

<!-- -------------------------------------------------------------------------------------- -->

    <hr />
    <a href="{% url 'second:second_list' %}">목록으로</a>

    <a href="{% url 'second:post_edit' second_detail.pk %}">
        댓글 수정하기
    </a>
{% endblock %}

django/mydjango19_1/second/templates/second/second_list.html
{% extends 'second/layout.html' %}

{% block content %}
    <form action="" method = "get">
        <input type="text" name="query" value="{{request.GET.query}}"
            placeholder = "검색어를 입력해주세요." />
        <input type="submit" value= '검색' />
    </form>

<!-- -------------------------------------------------------------------------------------- -->

<!-- 1> ul>li*2    2> div(class(style)) 3> img(img(src,slt,class)) -->
    <div class="row" style="margin-top: 1em;">
        {% for second in second_list %}
        <div class = "col-sm-6 offset_sm_3" style='margin-bottom: 1em;'>
            <div class="card">
                <img src="{{second.photo.url}}" 
                    alt="{{second.title}}"
                    class = "card-img-top">
                <div claa = "card_body">
                    <h5 class = "card-title">{{second.title}}</h5>
                    {{second.content|truncatewords:2}}
                    <a href="{% url 'second:second_detail' second.pk %}" 
                    class = "btn btn-sm btn-primary">
                    바로 가기
                    </a>
                </div>
            </div>
        </div>     
    {% endfor %}
    </div>

    <a href="{% url 'second:post_new' %}"
            class = "btn btn-primary"> 가자</a>

{% endblock %}
<!-- -------------------------------------------------------------------------------------- -->

django/mydjango19_1/second/templates/second/tag_detail.html
{% extends 'second/layout.html' %}

{% block content %}
    <h2>{{tag_name}}</h2>

    <div>
        {% for second in second_list %}
            <div>
                {{second.tite}}
            </div>
        {% endfor %}
    </div>

{% endblock %}