homework/myhomework20/diary/urls.py
from django.urls import path
from . import views


app_name = 'diary'

urlpatterns = [
    path('',views.post_list, name = "post_list"),
    path('<int:pk>/',views.post_detail,name = "post_detail"),
    path('tags/<str:tag_name>/',views.tag_detail,name="rag_detail"),
    path("new/", views.post_new,name='post_new'),
]

homework/myhomework20/diary/models.py
from django.db import models

class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_At = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True # 추상 클래스로서, DB테이블이 생기지 않는다.

class Post(TimestampedModel):
    author_name = models.CharField(max_length=20)
    title = models.CharField(max_length=200, db_index = True)
    content = models.TextField()
    photo = models.ImageField(upload_to = 'diary\post\%Y\%m\%d')
    tag_set = models.ManyToManyField("tag", blank = True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "포스팅"
        verbose_name_plural = "포스팅 목록"


class Comment(TimestampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=20)
    messge = models.TextField()

    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글 목록"


class Tag(TimestampedModel):
    name = models.CharField(max_length=200, db_index=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그 목록"

homework/myhomework20/diary/forms.py
from django import forms
from django.core.validators import RegexValidator


class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField()
    phone = forms.CharField(
        validators=[
            RegexValidator(r"^\d{3}-?\d{4}-?\d{4}$", message="휴대폰 번호를 입력해주세요."),
        ]
    )

# from django import forms
# from diary.models import Post

# class PostForm(forms.Modelform):
#     class Meta:
#         models = Post
#         fields = "__all__"

homework/myhomework20/diary/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse
from diary.models import Post
from diary.forms import PostForm

def post_list(request:HttpRequest)-> HttpResponse:
    template_name = 'diary/post_list.html'
    post = Post.objects.all()
    query = request.GET.get("quert","")
    if query == "GET":
        post = post.filter(title__icontains=query)
    context_name = {'post_list':post,}
    return render(request , template_name , context_name)

def post_detail(request:HttpRequest, pk:int) -> HttpResponse:
    template_name = 'diary/post_detail.html'
    post = Post.objects.get(pk=pk)
    comment_list = post.commir_set.all()
    tag_list = post.tag_set.all()
    context_name = {'post_detail':post,
                    'comment_list':comment_list,
                    'tag_list':tag_list,}
    return render(request, template_name , context_name)

def tag_detail(request:HttpRequest, tag_name:str) -> HttpResponse:
    template_name = 'diary/tag_detail.html'
    post = Post.objects.all()
    post = post.filter(tag_set__name = tag_name)
    context_name = {'tag_name':tag_name,
                    'post_list':post,}
    return render(request,template_name, context_name)


def post_new(request:HttpRequest)-> HttpResponse:
    form = PostForm()
    return render(request, 'diary/post_form.html',
    {"form":form,})

homework/myhomework20/diary/templates/diary/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>누구누구의 페이지</title>
    
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src = '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js'></script>

    <style>
        body {
            padding-bottom: 1em;
        }
    </style>
    
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="{% url 'root' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-danger text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
              <span class="fs-4">누구누구의 page</span>
            </a>
      
            <ul class="nav nav-pills">
              <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
              <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
              <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
              <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
              <li class="nav-item"><a href="#" class="nav-link">About</a></li>
            </ul>
          </header>
    
    </div>
    
</head>
<body>
    <div class="container">
        <h1>누구누구의 다이어리</h1>
        {% block content %} {% endblock %}

        <hr />
        &copy; 누구누구의 컴퍼니
    </div>
    
</body>
</html>

homework/myhomework20/diary/templates/diary/post_detail.html
{% extends 'diary.layout.html' %}

{% block content %}
    <h2>{{post.title}}</h2>

    <!-- 태그 목록 추가 -->
    <p>
        태그:
        {% for tag in tag_list %}
        <span claa = "badge bg-success">
            <a href="{% url 'diary:tag_detail' tag.name %}">
                {{ tag.name }}
            </span>
            </a>
            
        
        {% endfor %}
    </p>

    <img src="{{post.photot.url}}" alt="{{post_detail.title}}">

    {{post.content|linebreaks}}

    <!-- 댓글 추가 -->
    <ul>
        {% for comment in comment_list %}
        <li>
            {{ comment.message }}
            by {{ comment.author_name }}
            at {{ comment.created_at }}
        </li>
        {% endfor %}
    </ul>

    <hr />
    <a href="{% url 'diary:post_list' %}">
        목록으로
    </a>
{% endblock %}

homework/myhomework20/diary/templates/diary/post_form.html
{% extends 'diary/layout.html' %}

{% block content %}

    <h2>Post Form</h2>
    <table>
    {{ form.as_table }}
    </table>
    {% endblock %}

homework/myhomework20/diary/templates/diary/post_list.html
{% extends 'diary/layout.html' %}

{% block content %}

    <div class="container">
        <form action="" method = "get" enctype="multipart/form-data">
            <input type="text" 
                name = 'query' 
                value= "{{ request.GET.query }}"
                placeholder="검색어를 입력해주세요." />
            <input type="submit" value="검색"/>
        </form>
    </div>
        
        <!-- 전체 박스 만들기 -->

    <div class = "row" style="margin-top: 1em;">
        {% for post in post_list %}
        <div class="col-sm-6 offset-sm-3" style="margin-bottom:1em;">
            <div class="card">
                <img src="{{post.photo.url}}" 
                alt="{{post.title}}"
                class = "card-img-top">

                <div class="card-body">
                    <h5 class = "card-title">{{ post.title }}</h5>
                    {{ post.content|truncatewords:20 }}
                    <a href="{% url 'diary:post_detail' post.pk %}" 
                    class = "btn btn-sm btn-primary"> 
                    바로가기 
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <a href="{% url 'diary:post_new' %}"
        class = 'btn btn-primary'>
    포스팅 쓰기</a>


{% endblock %}

homework/myhomework20/diary/templates/diary/tag_detail.html
{% extends 'diray/layout.html' %}

{% block content %}
    <h2>{{tag_name}}</h2>

    <div>
        {% for post in post_list %}
        <div>
            <a href="{% url 'diary:post_detail' %} post.pk">
                {{ post.title }}
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}